### ISSUE TITLE
No translation available

### ISSUE THREAD

**Issue by tobir** [cloos/RT-Extension-AddAttachmentsFromTransactions#1]
Hi Christian,

this is more a feature request than a bug report.
After installing this Addon to our mostly German RT-installation, I realized, that there is no translation available. I'd like to have 'Include attachments' in german, so I replaced the strings in BeforeSubmit and End with 'Vorhandenen Anhang mitschicken'.
I know, that updating your plugin breaks the translation, so can you please make it possible to include e.g. a 'de.po' file for the translations?

Best regards,
Tobi

**Comment by netsandbox** [comment]
Hi Tobi,

I never wanted to add a translation file for a single translation string.
Because you can change and add translations easily in RT, without messing up the code in an extension or even core RT.
Just add under `/opt/rt4/local/po/` (RT::LocalLexiconPath) a new file `de.po`with the following content:
```
msgid "Include attachments"
msgstr "Vorhandenen Anhang mitschicken"
```
You actually have to revert the changes to the code of my extension to make this work.

Christian
